# 1.Print 'Hello HCIA'.

In [2]:
print("Hello HCIA")

Hello HCIA


# 2.Define two variables and calculate their sum.

In [3]:
a = 3
b = 5
print(a + b)

8


# 3.Define a list and replicate in three different ways.

In [19]:
import copy
ls = [1,2,3]
ls1 = ls
print (ls1)
ls2 = list.copy(ls)
print(ls2)
ls3 = list(ls)
print(ls3)

[1, 2, 3]
[1, 2, 3]
[1, 2, 3]


# 4.Define two lists and merge them together.

In [5]:
a = (1 , 2)
b = (3, 4)
print(a+b)

(1, 2, 3, 4)


# 5. Get the last element of the list and print it.

In [11]:
a = (0, 1, 3, 4)
print(a [-1])

4


# 6.Define a tuple that contains only one element.

In [17]:
tuple = [1000]

print(tuple[0:])


[1000]


# 7.Define a three-line long string.

In [22]:
a = ("sadsa")
b = ("asdsad")
c = ("asdas")
print (a + b + c)

sadsaasdsadasdas


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [16]:
tuple = (1, 2, 3, 4, 5)

print(tuple[0:])


(1, 2, 3, 4, 5)


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [14]:
def mul (x, y):
    return x * y
print(mul(8,6))

48


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [15]:
import numpy as np
a = np.array((5, 5))
print(a)

[5 5]


# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [19]:
import numpy as np
c = np.zeros((4, 6))
print(c)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [29]:
a = np.arange(15)
print(a.reshape(3, 5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [37]:
import numpy as np
matrix1 = np.array([ [1, 2], [3, 4] ])
matrix2 = np.array([ [5, 6], [7, 8] ])
total = matrix1 * matrix2
print(total)

[[ 5 12]
 [21 32]]
